[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.22.2"

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
